apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-go-kdrjboik
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tsscui/backend-tests-go-kdrjboik:b54310c374a15c75f44afdb66e0d3ce65b5079ce
          name: container-image
